#
# (c) Copyright 2021 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  filestore-service:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-filestore-service${ISOL_DOCKER_VERSION_SEP}${ISOL_VERSION}
    networks:
      - main
    volumes:
      - filestore-service-data:/data
    ports:
      - ${ISOL_FILESTORE_SERVICE_DOCKER_PORT}:8000
    environment:
      - SCALITY_ACCESS_KEY_ID=${ISOL_FILESTORE_SERVICE_USERNAME}
      - SCALITY_SECRET_ACCESS_KEY=${ISOL_FILESTORE_SERVICE_PASSWORD}

volumes:
  filestore-service-data:

networks:
  main:
