#
# Copyright 2021-2023 Open Text.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Open Text and its affiliates
# and licensors ("Open Text") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Open Text shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  ui:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}lema-ui${ISOL_DOCKER_VERSION_SEP}${UI_VERSION}
    networks:
      - main
    volumes:
      - ${LEMA_UI_TLS_CERT_DIR}:/etc/nginx/ssl
    ports:
      - ${LEMA_UI_DOCKER_PORT}:${LEMA_UI_INTERNAL_PORT}
    environment:
      - ISOL_EXTERNAL_PROTOCOL=${ISOL_EXTERNAL_PROTOCOL}
      - ISOL_API_SERVICE_EXTERNAL_HOST=${ISOL_API_SERVICE_EXTERNAL_HOST}
      - ISOL_API_SERVICE_EXTERNAL_PORT=${ISOL_API_SERVICE_EXTERNAL_PORT}
      - ISOL_API_SERVICE_EXTERNAL_PATH=${ISOL_API_SERVICE_EXTERNAL_PATH}
      - LEMA_UI_EXTERNAL_HOST=${LEMA_UI_EXTERNAL_HOST}
      - LEMA_UI_EXTERNAL_PORT=${LEMA_UI_EXTERNAL_PORT}
      - LEMA_UI_EXTERNAL_PATH=${LEMA_UI_EXTERNAL_PATH}
      - ISOL_AUTH_SERVICE_REALM=${ISOL_AUTH_SERVICE_REALM}
      - ISOL_AUTH_SERVICE_UI_CLIENT=${ISOL_AUTH_SERVICE_UI_CLIENT}
      - ISOL_AUTH_SERVICE_EXTERNAL_HOST=${ISOL_AUTH_SERVICE_EXTERNAL_HOST}
      - ISOL_AUTH_SERVICE_EXTERNAL_PORT=${ISOL_AUTH_SERVICE_EXTERNAL_PORT}
      - ISOL_AUTH_SERVICE_EXTERNAL_PATH=${ISOL_AUTH_SERVICE_EXTERNAL_PATH}
